[first]
# Min horizontal distance between peaks.
thr_min_peak_horizontal_distance = 10_000

# Min width of peak to consider.
thr_min_peak_width = 20

# Min horizontal distance between valleys.
thr_min_valley_horizontal_distance = 10_000

# Min width of valley to consider.
thr_min_valley_width = 10

# Number of std above mean to include peak.
thr_peak_height_std_above = 4

# Number of std below mean to include valley.
thr_valley_height_std_below = 3

[second]
# Percent threshold of most freq base to allow second most freq base
# 30 * 0.1 = 3 so above 3 is allowed.
thr_min_perc_first = 0.1

# Number of std above mean to include peak.
thr_peak_height_std_above = 3

# Group consecutive positions allowing a maximum gap of x.
# Larger value groups more positions.
group_distance = 30_000

# Min group size.
thr_min_group_size = 20

# Het ratio to consider second group a collapse if no overlaps in peaks found.
thr_collapse_het_ratio = 0.2
