[first]
# Min width of peak to consider.
thr_min_peak_width = 20

# Min width of valley to consider.
thr_min_valley_width = 5

# Valleys with height above this threshold are considered misjoins.
thr_misjoin_valley = 0.95

# Peaks with height above this threshold are considered collapses.
thr_collapse_peak = 2.5

# Group consecutive positions allowing a maximum gap of x.
# Larger value groups more positions.
valley_group_distance = 5_000

peak_group_distance = 5_000

[second]
# Percent threshold of most freq base to allow second most freq base
# 30 * 0.1 = 3 so above 3 is allowed.
thr_min_perc_first = 0.05

# Group consecutive positions allowing a maximum gap of x.
# Larger value groups more positions.
group_distance = 30_000

# Min group size.
thr_min_group_size = 5

# Regions with a het ratio below this are hets. Otherwise, considered an error.
thr_het_ratio = 0.2

[general]
# Window size. Only applicable if no region bed file is provided.
window_size = 5_000_000
